### ISSUE TITLE
Background process status lags by one prompt

### ISSUE THREAD

**Issue by yongqli** [caiogondim/bullet-train.zsh#137]
If you type

```
$ top %
```

followed by

```
$ kill %%
```

it still shows the gear icon on the prompt. I would expect it to be more like <a href="https://cloud.githubusercontent.com/assets/2618447/6316862/70f58fb6-ba03-11e4-82c9-c083bf9a6574.png">this</a>.

**Comment by dawikur** [comment]
@yongqli is this issue occurs for you on master? Can you specify your setup? I checked it briefly and it is working fine for me.

**Comment by yongqli** [comment]
Just tested and it's working now.
