### ISSUE TITLE
Can't get it work

### ISSUE THREAD

**Issue by vladyn** [caiogondim/bullet-train.zsh#200]
Hello there, 
first to say - this theme is really rocks! I Installed the oh my zsh because of it. I followed the install instruction, got the fonts, but for some reason I'm not getting same result: 
<img width="1069" alt="screen shot 2017-02-07 at 8 29 59 pm" src="https://cloud.githubusercontent.com/assets/107272/22707815/4f705406-ed74-11e6-8c78-adb36ddc2a1d.png">

**Comment by philipesteiff** [comment]
Same here :(

**Comment by caiogondim** [comment]
You have to set the font in the configurations.
I made a vide to explain the process: http://cl.ly/1k2e302S2Z2s

Let me know if it solved your problem.

**Comment by aarree** [comment]
Hi,
Solved the problem not completetly form me. Now looks like this:
![image](https://cloud.githubusercontent.com/assets/11751109/22731750/ffdc77f8-edeb-11e6-8a88-41a671a8024f.png)
Thanks for the Video

**Comment by caiogondim** [comment]
What's the current problem?
The black segment?

**Comment by aarree** [comment]
yes, plus colors look very different. Just wanted them like in the preview.

**Comment by caiogondim** [comment]
I would highly recommend for you to use [iTerm](https://www.iterm2.com/) instead of Terminal.app

If you want the colors as the preview, you will need a theme.
I use this one https://github.com/chriskempson/tomorrow-theme/tree/master/iTerm2

Regarding the segment, when you change the theme it should be fixed.

**Comment by aarree** [comment]
Thank you! All working now!
