### ISSUE TITLE
Terminal color scheme

### ISSUE THREAD

**Issue by luna-lu** [caiogondim/bullet-train.zsh#202]
Hi,
I have been trying to figure out which color scheme you used in the screenshot, but I couldn't find it.  It would be nice if you could describe more info about color scheme on README.md, thanks.

**Comment by sfarzy** [comment]
It's available on the [screenshots page](https://github.com/caiogondim/bullet-train.zsh/wiki/Screenshots). It's [Tomorrow Night Eighties](https://github.com/caiogondim/bullet-train.zsh/wiki/Screenshots#tomorrow-night-eighties)

**Comment by luna-lu** [comment]
Oops! Thanks, you are the best!

**Comment by jasonwilliams** [comment]
@vadviktor i know this issue is closed, but i think it would be good if you could mention this on the readme, i spent a while confused as to why my default setup didn't look the same as the screenshot. It can be  misleading

**Comment by vadviktor** [comment]
I am not using this version of Bullettrain anymore (wrote a Go version of it) and TBH, making notes on any colour schemes would be useless because they are terminal software specific. It really has nothing to do with this script.

**Comment by Frankcarvajal** [comment]
I wish I could just get the full `./zshrc` of the gif...
