### ISSUE TITLE
There is no gap between the $ and the prompt character

### ISSUE THREAD

**Issue by burhan** [caiogondim/bullet-train.zsh#205]
Not sure how to describe this issue, so here is a screenshot:

<img width="337" alt="screen shot 2017-02-19 at 9 00 53 pm 1" src="https://cloud.githubusercontent.com/assets/603112/23104890/5cd5e3be-f6e7-11e6-8e51-8b9d99a5ce0c.png">

Not sure what to do here, everything else is working fine. I have not customized any of the font options. iTerm2 version is `3.0.14`

I am using the `12pt Monoid Regular` font, which is already patched.

On my previous (non-lightbar) MacBook Pro, things are just fine.

**Comment by AlexTes** [comment]
Normal macOS terminal does it too. Didn't have this issue a couple weeks back.

**Comment by dawikur** [comment]
The space was removed in #162 and readded in #206.
Closing :smile:
