### ISSUE TITLE
git_prompt_info:5: character not in range again

### ISSUE THREAD

**Issue by Maethorin** [caiogondim/bullet-train.zsh#207]
I have installed bullet-train on several machines since last year, but today I started to get this error after installed in a new one.

I follow this tutorial: https://gist.github.com/renshuki/3cf3de6e7f00fa7e744a

But I used the bullet-train theme and stop the tutorial after change the theme.

After a little research, I found the problem is at https://github.com/caiogondim/bullet-train.zsh/blob/master/bullet-train.zsh-theme#L214

In my computer, I got a ? symbol where the powerline character should be:

![screenshot from 2017-03-03 11-59-47](https://cloud.githubusercontent.com/assets/98571/23555763/ec7eb552-0008-11e7-869f-8766394bcec2.png)

I tried a lot of things: reinstall powerline fonts, wget bullet-train's commits from jan, install all powerline fonts, export LC to en_US.UTF-8, locale-gen to en_US.UTF-8 but nothing works...

Dunno how to solve this, but I think the character you are using to show git untrack and git modified are not present at the current version of powerline or I have another issue with this new installation of Ubuntu 16.04 with Terminator... maybe a new version of Terminator because the others machines are still OK.

TKS!

**Comment by dawikur** [comment]
I am using Arch linux and had quite a lot a trouble with few characters used by default in bullet-train. Currently my font is [nerd-fonts](https://github.com/ryanoasis/nerd-fonts)-patched DroidSans. I am afraid that some of  the default characters may be mac-only.

**Comment by vadviktor** [comment]
@Maethorin I personally added the name of the package in the README in the requirements section.
What you need under Ubuntu is the `ttf-ancient-fonts` package to get the font chars right, no matter what font you use. 😉 

Let me know if this solves it so we can close this issue.

**Comment by yongqli** [comment]
I'm having a similar issue, but for me it only happens when I'm `ssh`ed into a `tmux` session on an macOS machine. Any ideas?

**Comment by IceMimosa** [comment]
I'm having the same issue in IDEA, but strangely not in iTerm2.

**Comment by vadviktor** [comment]
@IceMimosa IDEA's terminal is a completely separate beast. I for one, use a trick to load a more simplified theme in there. This theme is for sophisticated terminals.

**Comment by IceMimosa** [comment]
@vadviktor Thanks for you reply. I found the problem because IDEA cannot recognize **ZSH_THEME_GIT_PROMPT_PREFIX**. I'm confused, then i changed it violently. 😂

**Comment by vadviktor** [comment]
@IceMimosa for that issue, I have this in my `.zshrc`:

```shell
if [ -z $COLORTERM ]; then
  ZSH_THEME="simplex"
else
  ZSH_THEME="bullet-train"
fi
```

**Comment by dawikur** [comment]
Can be closed?

**Comment by Maethorin** [comment]
Yep,

Tks!

Em 16 de mai de 2017 2:34 PM, "Dawid Kurek" <notifications@github.com>
escreveu:

**Comment by dawikur** [comment]
Great!

**Comment by hg8** [comment]
Hello,
I am still having this issue using Termite.

    git_prompt_info:5: character not in range

The strange thing is that it works perfectly with same config file on my other computer :thinking: 

I have installed `ttf-ancient-fonts` and `powerline-fonts-git`.

The font I am using in Termite is `Source Code Pro for Powerline`.

Does anyone know what I may be missing ? 
Thanks in advance for your help.

**Comment by wuotr** [comment]
I solved this issue by manually specifying the environment language (by including the following lines on top in my `.zshrc` file):
```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

Hope it may help you too 😉.

**Comment by weklund** [comment]
@wuotr Thanks for the find!

**Comment by alexisortiz** [comment]
@wuotr Good Job! 🤘
