### ISSUE TITLE
Why does the node version always appear?

### ISSUE THREAD

**Issue by uyu423** [caiogondim/bullet-train.zsh#208]
![2017-03-09 11-08-18](https://cloud.githubusercontent.com/assets/8033320/23732822/c368e354-04b8-11e7-8b08-06a6840495c9.png)

Why does the node version always appear?

**Comment by uyu423** [comment]
There is currently a problem with the .zsh-theme file in the git master brunch.
It works as a file in the release and works normally.

**Comment by lans98** [comment]
How to solve this?

**Comment by vadviktor** [comment]
@uyu423 it is not broken, it should appear unless it is turned off. Prompts should appear even outside projects to show global interpreters anywhere in the system. I should not need to go into a folder to let me see what version of node I will lunch in e.g. a REPL.

**Comment by uyu423** [comment]
I think this problem will be resolved soon.

**Comment by uyu423** [comment]
@vadviktor  I think the node version should only be printed where it is needed.

**Comment by vadviktor** [comment]
@uyu423 this "need" is very much dependent on the users. I always advocate for displaying it always unless turned off, others want a more dynamic appearance behaviour. It would be great if you could add some great suggestions to please both kinds of needs, even if it's doable by feature flags or any other way.
Feel free to share your ideas in a separate issue and let's mark that an improvement discussion somehow.

**Comment by uyu423** [comment]
@vadviktor In fact, the problem I was experiencing was that when I used the bullet-train of the master branch, the node version was printed in a location that was not related to the node project. Even the Python project has printed the node version. (I think this is a temporary problem) Using release 0.0.5, the problem of unnecessary node version output is gone.

**Comment by unluisco** [comment]
I also have this problem, I dont need to see always the version of node.

**Comment by aniforprez** [comment]
There used to be an option where you could decide if you wanted to show the version of node but I don't see that option anymore in the docs and adding it does nothing anymore. Why was it removed? I don't ALWAYS need to see the version of node that's running so give users the option again to choose

**Comment by dbkaplun** [comment]
The node prompt should only appear when there is a package.json file in a containing directory. Anyone willing to make this change?

BTW @aniforprez you can remove the node version from your prompt in ~/.zshrc:
```sh
export BULLETTRAIN_PROMPT_ORDER=(${BULLETTRAIN_PROMPT_ORDER:#(context|ruby|nvm)}) # removes context, ruby, and nvm
```

**Comment by vadviktor** [comment]
@aniforprez it is there, in the zshrc file I have something like this:

```
BULLETTRAIN_PROMPT_ORDER=(
    time
    status
    custom
    context
    dir
    #perl
    ruby
    virtualenv
    #nvm
    #aws
    #go
    #elixir
    git
    #hg
    cmd_exec_time
  )
```

where in the list `nvm` (node version manager) is commented out, disabled.

`_SHOW` variables are now fully deprecated and we are concentrating the ability in that single option above. That way we can decide order AND availability.

Please feel free to make improvements to the README so users like yourself could find such answers for their questions. :)

**Comment by aniforprez** [comment]
Ah that makes sense. Since it's not explicitly specified in the README I was confused.

**Comment by philFernandez** [comment]
I noticed the same thing, and I also don't care for having my node version statically shown on the prompt. I also noticed that with GO it seems to have the desired functionality, meaning that the GO prompt section is only shown when in a directory containing GO source files. I modified the prompt_nvm function in the bullet-train.zsh-theme file to work the same as the one for GO. For anyone wanting this functionality all you need to do is open the bullet-train.zsh-theme file with a text editor, find the prompt_nvm function, and replace it with the modified version below, then reload zsh. Now it will only show your node version if you're in a directory containing either *.js files or *.json files. 

```bash
prompt_nvm() {
  if [[ (-f *.js(#qN)) || -f *.json(#qN) ]]; then
    local nvm_prompt
    if type nvm >/dev/null 2>&1; then
      nvm_prompt=$(nvm current 2>/dev/null)
      [[ "${nvm_prompt}x" == "x" ]] && return
    elif type node >/dev/null 2>&1; then
      nvm_prompt="$(node --version)"
    else
      return
    fi
  nvm_prompt=${nvm_prompt}
  prompt_segment $BULLETTRAIN_NVM_BG $BULLETTRAIN_NVM_FG $BULLETTRAIN_NVM_PREFIX$nvm_prompt
  fi
}

```

**Comment by caiogondim** [comment]
@philFernandez Could you make a PR?

**Comment by pm0u** [comment]
This may be slightly off topic, but @philFernandez solution above does not work for me.. it seems to be an issue with the conditional statement
`if [[ (-f *.js(#qN)) || -f *.json(#qN) ]]`

to test evaluation, it seems any simple conditional involving the wildcard character will not expand for me. For instance in my home directory:
`[[ -f * ]] && echo true`
prints nothing (there are files present). while in the same directory
`[[ -f .zshrc ]] && echo true` 
prints true. Can anyone offer any advice? I'm at a loss.

**Comment by eduardotkoller** [comment]
@pm0u I know this is old, but @philFernandez solution needed one more line for me: `setopt extended_glob` before the if.

```sh

prompt_nvm() {
  if [[ (-f *.js(#qN)) || -f *.json(#qN) ]]; then
    setopt extended_glob
    local nvm_prompt
    if type nvm >/dev/null 2>&1; then
      nvm_prompt=$(nvm current 2>/dev/null)
      [[ "${nvm_prompt}x" == "x" ]] && return
    elif type node >/dev/null 2>&1; then
      nvm_prompt="$(node --version)"
    else
      return
    fi
    nvm_prompt=${nvm_prompt}
    prompt_segment $BULLETTRAIN_NVM_BG $BULLETTRAIN_NVM_FG $BULLETTRAIN_NVM_PREFIX$nvm_prompt
  fi
}
```

**Comment by pm0u** [comment]
@eduardotkoller thanks man! that did it. that probably explains the expansion issues I was having.

**Comment by alexklann** [comment]
So this is still not fixed after 4 years?

![image](https://github.com/caiogondim/bullet-train.zsh/assets/47794032/0553ce83-f916-4be3-b374-93a3c6b20dfe)

Not in a node project in this screenshot

**Comment by uyu423** [comment]
@Libroru For reference... I defected to powerlevel10k 😢 https://github.com/romkatv/powerlevel10k
