### ISSUE TITLE
Weird characters

### ISSUE THREAD

**Issue by ncnthuy** [caiogondim/bullet-train.zsh#219]
![image](https://cloud.githubusercontent.com/assets/2102816/26088816/3c70279a-3a23-11e7-979e-0b23d3d8b9a2.png)
When I installed, I see weird characters like above pictures. Please help me to fix this.

**Comment by sfarzy** [comment]
Please try installing a powerline patched font. See more info in [requirements](https://github.com/caiogondim/bullet-train.zsh#requirements) section.

**Comment by ncnthuy** [comment]
I installed powerline patched font. But it seem to be not working. Currently, I used terminal with oh-my-zsh of OSX Sierra

**Comment by sfarzy** [comment]
Did you change the font settings in your terminal ?

**Comment by ncnthuy** [comment]
Ok! Thanks for your help. I changed to Powerline fonts, and It's works now!

**Comment by dawikur** [comment]
Closing
