### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by pabclsn** [caiogondim/bullet-train.zsh#222]
Hi guys, my terminal looks like this, I installed oh-my-zsh, nvm, nodejs. I don't know what to do now...
<img width="313" alt="capture d ecran 2017-05-20 a 20 12 11" src="https://cloud.githubusercontent.com/assets/25625769/26278350/a10cdda6-3d98-11e7-8ae7-f02651808801.png">

**Comment by dawikur** [comment]
Did you install and set proper fonts? Take a look at #219

**Comment by ruizhipeng** [comment]
how to hide the version, it is no use to me , if you know that ，please tell me how to do , thx

**Comment by vadviktor** [comment]
For now just use the `BULLETTRAIN_PROMPT_ORDER` and add only segments you wish to use. Others will not appear.
