### ISSUE TITLE
Display color issue

### ISSUE THREAD

**Issue by xnxky** [caiogondim/bullet-train.zsh#230]
Please check the following snapshot in iterm2 of Macbook; The middle color is black; 

<img width="740" alt="screen shot 2017-06-27 at 6 47 55 pm" src="https://user-images.githubusercontent.com/1526944/27617160-72c5b366-5b69-11e7-9b13-7f8504cec5b2.png">

**Comment by dawikur** [comment]
And what do you expect it to be? Default value of `BULLETTRAIN_CONTEXT_BG` *is* `black`

**Comment by xnxky** [comment]
Yep, got it. I was new to this, not familiar with all the settings. Thanks.
