### ISSUE TITLE
hostname isn't showing?

### ISSUE THREAD

**Issue by yifanchen** [caiogondim/bullet-train.zsh#233]
Hi there, I turned on the `BULLETTRAIN_CONTEXT_HOSTNAME="true"`, sourcing, don't see then change, is there something else I need to enable?

**Comment by vadviktor** [comment]
Hey @yifanchen I'd suggest you read the README and understand it's description, but let me help you there:

> BULLETTRAIN_CONTEXT_HOSTNAME | %m | Hostname. Set %M to display the full qualified domain name.

It says you can set it to `%M` other than the default `%m`. Knowing a little shell is required (and Googling if needed) to know what those chars mean.

If you set this env var to `true` as you mentioned I bet you realised hostname is now showing `true`. Change it to other string and will show just that.

So let's just set it to what we suggest in the readme and you'll be fine.
I hope that helps you understand this software better and make you appreciate it's design :)
