### ISSUE TITLE
Bullet-train.go

### ISSUE THREAD

**Issue by vadviktor** [caiogondim/bullet-train.zsh#236]
Hey,

so earlier we were talking about maybe rewriting Bullettrain in some higher level language and I fancied that idea very much because shell scripts are hard to understand, have too much quirks and really hard to make cross scripting work.

I know Bullettrain is a ZSH initiative now, though with choosing a higher level language that is at least Linux and Mac friendly would benefit us all not only in creating new features but in hunting down bugs.

There is now a Slack chat and a new project attached to this cause. I myself have done some research on possible candidates (https://gist.github.com/vadviktor/c7c96ec9e6df9d34803830f847866cd8).

Giving it much thought I as one want a language that:

- very much platform portable
- community friendly
- very snappy to boot up and also runs fast
- not hard to learn (like C or such)
- may not require additional tools to be installed to use

Out of these criteria Go came out as a winner and Python as an optional second. Though, I am ditching Python as v2 is going away soon and v3 is still seeing bleeding edge constructs around it's concurrency libs.

So all that said I have started to learn and write the first prototype of the new Bullettrain prompt, which I later towards v1.0 want to be:

- snappy as hell (concurrent/parallel)
- plugin and configuration friendly, easy to extend
- well documented end user/dev wiki

Should no one would be interested I still wish to ask @caiogondim to let me create this as part of the Bullettrain project.

Your thoughts, suggestions, contributions are very welcome!

@gregf @kamui @dawikur @jeremyFreeAgent @jocelynmallon @unixorn @Arthraim @revolter @ThamosIO @mariozig @flavius @jtyr @faceleg (and all the rest who uses it, the list is just too long)

**Comment by gregf** [comment]
Very interested in this. I already know go and love the language. Please keep us updated as there's a branch ready to play with and I'll contribute.

**Comment by vadviktor** [comment]
Since I imagine this Go project to be having segment plugins, I'd set up a `bullettrain-go-core` repo holding the spine of it, in the organization https://github.com/bullettrain-sh.

Then the segments that are not fundamental to the OS, like Python or Ruby, etc would go into separate repos like `bullettrain-go-python`, `bullettrain-go-ruby`, etc.

I'd say segments should stay out of the core as they could be very specific internally, e.g. Python or Ruby version managers need to be tested what other people won't even use but only that segments' contributors.

Defining a good set of interfaces will help other segment repos to be created in a very straight forward manner. Like there should be a single interface method that renders the segment and describes a unified set of inputs and outputs, possibly no variadic parameters needed.

I also wanted to tell you that I see this project to be brought to the Bash users as well as it is going to be a single executable and won't use shell specific calls.

I shall wait for more input on this idea from the others and get my code and docs out later.

**Comment by gregf** [comment]
All sounds like a good idea to me @vadviktor

**Comment by dawikur** [comment]
Sounds good. It will be nice to separate core functionality from segments, and we can also pull out OS specifics. 👍

**Comment by gregf** [comment]
It would be nice to make this work on both bash and zsh too if we are going that route. I don't think it would take a lot of extract work to do so.

**Comment by vadviktor** [comment]
And tell you what, my first attempts work on both Bash and ZSH :)

**Comment by vadviktor** [comment]
I have created the core repo and imported all the work I currently have: https://github.com/bullettrain-sh/bullettrain-go-core

From here we can move forward and elaborate on ways to move forward. I will write the tasks to be done in issues and we can collaborate through those, track PRs, etc. Also it would summarise requirements/roadmap ideas. I think ;).

**Comment by vadviktor** [comment]
Going through some PRs here I am seeing that each segment will need detailed documentation how if should work, and accommodate the "show-on-demand" feature as well.

**Comment by dawikur** [comment]
Yeah, wiki pages might be easier to put together, but this project is so much about style, right? Probably nice looking page with good links and descriptions, examples will be better. Jekyll can be utilize.

**Comment by vadviktor** [comment]
I envision a great and visually appealing project site, and use the wiki's per module to aid development and use, FAQs, quirks.

**Comment by ThamosIO** [comment]
Hey @vadviktor, very cool initiative. I don't know go but I will follow closely and will try to help if I can 👍

**Comment by vadviktor** [comment]
Hey @ThamosIO I don't know go very well myself, though this is a perfect opportunity to do so 😋

**Comment by vadviktor** [comment]
Anyone good at creating good looking frontends? Preferably we could use a simple but great showcasing of different segments of this prompt customization. I don't feel animations, gifs worth it, but small and specific screenshot parts would better suit the cause. Even screenshots from different terminals and systems, like Mac iTerm or Linux Konsole.

**Comment by vadviktor** [comment]
@gregf since you mentioned you know Go, could you have a look at my channel solution for https://github.com/bullettrain-sh/bullettrain-go-core and https://github.com/bullettrain-sh/bullettrain-go-python please?

**Comment by gregf** [comment]
@vadviktor channels look good at a glance. I can put some time into this project if you want to add me as a collaborator?

**Comment by gregf** [comment]
As far as front ends go. I can take some Linux screen shots when we have it working. As far as styling I say we keep things looking very similar to the existing bullet train for now at least. We can make changes as we go, but for simplicity, it would be best to just port what we have now and add features after the fact.

**Comment by vadviktor** [comment]
@gregf that is why I started this Go variant with reaching out to you all is to feel free to contribute in any way you can, putting lines in the readme, rephrasing sentences too would greatly help.

For the screenshots and looks, I want it to look exactly the same as the zsh one is now, only fixing/extending segment functionality. I wish it'd be a 2 minute work to replace each other. 😉

**Comment by caiogondim** [comment]
I've been playing with a `next` bulletrain for quite a while, and I'm quite happy with the results.
Would like to share with you.

### Cars
bulletrain have cars (just like a train).
A car is a BASH function, and you set it on `BULLETTRAIN_CARS` env var, just like the current `BULLETTRAIN_PROMPT_ORDER`.

Create a BASH function, expose it, and put it on `BULLETTRAIN_CAR`.

Every car is responsible to:
- read env vars as input
- do it's output
- decide to show/hide itself

### Layout
I thought bulletrain was lacking some character.
It was feeling a lot like powerline.

So I decided to make it look more like a train and to use nerd fonts to avoid using emojis.

![screen shot 2017-07-31 at 2 56 21 pm](https://user-images.githubusercontent.com/33044/28793258-70651b6e-7600-11e7-8295-dfbde67382d1.png)

### 🚫  Emojis

No emojis anymore, but [nerd-fonts](https://github.com/ryanoasis/nerd-fonts).
Emojis are very colorful and gets too much attention IMHO.

With nerd-fonts we have a lot more symbols as well.

### Speed 
I made a comment on your benchmark suite https://gist.github.com/vadviktor/c7c96ec9e6df9d34803830f847866cd8

### Thoughts about Go

- Most of the work is I/O, like `git --version`. I doubt we would see a speed bump with Go. Maybe running the cars in parallel.
- Compilation. We would have to compile for every combination of Operational System x processor architecture
- I hate BASH more than everything, but it's IMHO the best language for this job. Even though we as bulletrain developers don't have a great experience, it's better for our users.

### Thoughts about the org

We can move to the org and create different cars there.

**Comment by dawikur** [comment]
@caiogondim  Interesting to hear that you have already made some work on it as well 😄 
No emoji - I'm on! I have already replaced most of them with nerd-fonts, as on my Arch it wasn't really working.
With the 'new' look - I see how it looks, pretty nice. But I know that for me it would be a while before  would like to transition to the new one. It could be parameterized, right?

For the colors - I wonder If we can somehow play along with base16. I use it and having everything in one colorscheme looks great :)

**Comment by vadviktor** [comment]
OH I remember us talking in CARS before :)

OMG NERD FONTS!!! 😋

# Speed

* I am sure we would have to see speed increase - meaning: steady speed instead of any increase with new cars loaded. Go threads are leveraging OS threads while keeping everything in the userspace, making them "green" threads.

* We will compile and support only those systems we can have people to test, but since Go is very versatile, given the initial OS side requirements it should still behave better then us having to figure out shell script quirks. Unless new contributors having access to more variety of systems out there can provide testing, I would not support them by having us building them. Linux and Mac should be our highest priority first.

* Also since we are moving every string building logic into a higher level language, we won't have to be afraid of what differences Bash or Zsh, or others have.

# Question

Should I rename the separate modules to have cars in their names? What would be the naming template?

**Comment by vadviktor** [comment]
@dawikur

* colours: I believe only base16 should be provided by "words" that we can match but later I would see a feasible way to implement support for [X11 colours](https://en.wikipedia.org/wiki/X11_color_names) too.

* parameters: everything must be achievable through env variables like in the current implementation, I want to recreate and hopefully steady/fix their functionalities.

If it takes more then a few minutes to configure, set up this theme, it's a failure and the design needs some more love.

**Comment by vadviktor** [comment]
😈 after I we release v1 I will defo make a Golang meetup talk on the project here in Dublin (IE).

**Comment by vadviktor** [comment]
FYI please have a look at the updated benchmarks: https://gist.github.com/vadviktor/c7c96ec9e6df9d34803830f847866cd8

Clearly visible that even compared to the pure shell script version, the parallel Go version is magnitudes faster and will remain faster the more cars we attach, while sequential scripts will be slower.

**Comment by vadviktor** [comment]
I have made good progress and began to dogfood the project locally. If I will not find any new use cases uncovered already, I'll release the first beta at the end of Aug. You can follow the project in the organization page. https://github.com/bullettrain-sh

**Comment by jtyr** [comment]
Thanks for starting the new project, @vadviktor. I have tested it and it looks promising. What I'm currently missing is the Git car. Any idea when that will be available?

**Comment by vadviktor** [comment]
@jtyr My first concern until the beta is completing every possible core api/interface the cars could possibly need to achieve most flexibility. The only external (non-core) car I am testing it with is the python one, as I use it daily. The git car actually will need more input and help from the community, because I don't use it extensively and the only info I care about in it is to show me the current branch name.

I believe the core interface is good enough for anyone to start building the git car. Joining in the IRC channel on freenode `#bullettrain-sh` or on slack, could help any developer wishes to contribute as I'd need to discuss/elaborate on some design decisions to understand it better. Better yet they could suggest me a much better way to do things.

Before the end of September I won't promise any stable releases yet.

**Comment by vadviktor** [comment]
There is also a github project for the core where I am managing my development schedule for the first release. https://github.com/bullettrain-sh/bullettrain-go-core/projects/2

**Comment by vadviktor** [comment]
A screenshot of the new beginning in Konsole on ArchLinux.

![spectacle rb7845](https://user-images.githubusercontent.com/238703/29025145-4be707a8-7b6d-11e7-8513-01793f851e86.jpeg)

**Comment by vadviktor** [comment]
![spectacle w16171](https://user-images.githubusercontent.com/238703/29209830-7af40d8e-7e88-11e7-9baf-a0af86662547.jpeg)

Here is a new insight of the progress. You can see the even the separator (first one is a pipe) can be customised now one by one.
The only issue currently I have is that autocompletion guessing and offering indents the current cursor, and sometimes makes the half of the prompt disappear. I assume it is connected to the ZSH autocompletion directly. Also a slight issue is that BASH has problems displaying the prompt in single line mode. All in all it looks promising and it's still blazing fast.

**Comment by vadviktor** [comment]
Hey People,

I am making some pretty neat progress with the project and now it is considered beta version 😄  🎆 
Anyone interested in testing can shortly have a look as I will be releasing builds in the coming days.

The documentation is only bare minimum and lacks explanation of a good set of possibilities. Bare with me there.

For now, here is a snapshot of some new `cars`:

![spectacle b15914](https://user-images.githubusercontent.com/238703/29489947-fed8aef0-8524-11e7-9284-7bb4c4820fee.png)

**Comment by ryanoasis** [comment]
It's looking good 👍

**Comment by vadviktor** [comment]
First public beta is out https://github.com/bullettrain-sh/bullettrain-go-core/releases/tag/v0.5-beta

**Comment by jtyr** [comment]
I have created an Arch Linux package for this release:

https://aur.archlinux.org/packages/bullettrain

I have played with the settings a bit and couldn't figure out how to set:

1. Spaces around the car context and icon.
2. Different background/foreground color via escape sequences.
3. `dir` car showing only the last bit of the path.

Some examples of possible configurations would be much appreciated.

**Comment by vadviktor** [comment]
Hey @jtyr,

thank you very much for raising such good questions so early 👍 

1, Arch package

it warms my heart❤️ to see such love😍 being shown to the project nonetheless. Go is a static compiled language, so there will be no such support as dynamic extensions. The main program must be built with all required extensions added in code. Therefore you'll ever need to package the binaries for the respectful architectures and OSes. I'd suggest you do the same and package only the linux 386 and amd64 binaries with the sha checksums.

2, Spaces in icons

Every car has there own icon holder env var and you can play with additional spaces within them, they won't break or behave otherwise.

3, dir car

The cars defo need more documentation AND screenshots, which I was telling about above. This is no less work than writing the code itself. I'd need some patients on your side please 😃 
Whichever feature you'd expect is missing, please raise a ticket though. Even further questions could be better tracked and managed if you ask them there.

4, status car

Same as for the dir car, this feature is missing, please issue a ticket so I won't forget to implement and document it 👍 

5, config

since the software works off of env vars already being declared, I think it would be better to configure them before calling the prompt to be built. I am not a shell mage, don't know for really sure that this makes a different, but just in case it is parsed sequentially.

6, build tags

that's a really great note thank you! I'll make sure the new tags are 100% aligned.

7, support for new cars

as I said above, Go is statically linked, so I still need to document my idea in the readme as how it is possible for others to hack on the project and introduce their own plugins or just locally/privately hack together their very own software if they don't want to share.
I have heard it is somewhat possible to have external libs (compiled) being imported but that is never going to be supported by this project. The aim is to have a single executable to do the job. So everything has to be built in and instructed from the outside by command line args or env vars.


All in all thanks for the great feedback and I will continue working on the documentation.

**Comment by vadviktor** [comment]
Correction to above: will look into Go 1.8 plugin solution, but not promissing to use  such technics.

**Comment by jtyr** [comment]
I came across this blog post dealing with similar matter:

https://blog.bethselamin.de/posts/latency-matters.html

You could take some inspiration from there, @vadviktor ;o)

**Comment by jtyr** [comment]
Go plugins would be very useful as one of the biggest drawbacks of oh-my-zsh is the massive number of unmerged PRs. People would probably prefer to have the plugin in their own repo and manage it from there and users would only cherry pick plugins they want to use instead of having all possible modules built in. I think this is absolutely crucial feature for the future of this project.

**Comment by vadviktor** [comment]
@jtyr That is my exact plan and intention of building it most hackable. Actually it is already capable to do just that. I'll wait with the plugin system until the Go team stabilises it and then I'll consider using it. Until then, I'll just document thoroughly :)

As for the latency blog post you have linked, he had the same idea as I did, put aside every dangling runtime and dependency and make a single executable. In regards to performance, it is as slow as it's slowest car. Currently the Python car has some issues if pyenv is used. Currently I am trying to push through a PR with them https://github.com/pyenv/pyenv/pull/970

**Comment by jtyr** [comment]
Currently you can only add external cars by amending the `bullettrain.go` code to import and run the specific car. This requires recompilation. I was rather talking about importing whatever car is specified in the `BULLETTRAIN_CARS` env variable. That would require to use Go Plugins for all cars. Something like this (sorry, I'm not a Go developer):

```
for _, car := range o {
    p, _ := plugin.Open(Sprintf("/usr/share/bullettrain/%s_car.so", car)) 

    // Now add the car dynamically into the `trailers` list somehow.
    // Assuming all cars have the same interface to render them.
}
```

With this approach, if the user develops a new car, he can simply compile it as a plugin, place it into the specific directory and add the new car into the `BULLETTRAIN_CARS` env variable and all should magically work.

**Comment by vadviktor** [comment]
@jtyr I completely understand your point and idea. Though Go is not even like Java or C. You have no facility (yet that is stable) to do dynamic linking. 1.8 added some experiments but I would not develop against them. Go is staticly linked and that's how we are going to support it for now. I have began to document the development process https://github.com/bullettrain-sh/bullettrain-go-core/blob/master/docs/creating-new-cars.md.
Let's park this idea for now and I'll keep an eye on Go's advancement, whenever something comes to light I'll add in a new discussion as it will be a new breaking change in our software.
Let me remind you, any dynamic linking solution MUST be as performant as the static linking, otherwise it's no use to us. The end user is only interested in latency.

Users' also just need to recompile whenever they need to really tailor it to their needs. Whoever writes a plugin will know Go. They will know how to create a PR that adds their plugin to the software. Their plugin will only add to the size of the program to any who will switch it off from the env vars.

So right now I don't see any big drawbacks and I believe we can happily work with plugin writers and hackers will have a good documentation to create their own, super slim version.

**Comment by vadviktor** [comment]
Anyone interested in plugins, head over to this ticket https://github.com/bullettrain-sh/bullettrain-go-core/issues/31 and join the brainstorming.

**Comment by jtyr** [comment]
I just wanted to let you know that there are now two Arch Linux packages:

https://aur.archlinux.org/packages/bullettrain
https://aur.archlinux.org/packages/bullettrain-git

The first one is for binary releases and the second one is for the most recent development from the master branch.

**Comment by vadviktor** [comment]
Good job @jtyr ! I'm sure by the end of the week we could ship a v0.6 :)
