### ISSUE TITLE
The separator is shifted down

### ISSUE THREAD

**Issue by so77id** [caiogondim/bullet-train.zsh#239]
I just installed this theme in my macbook and in the OSX terminal the separator is shifted down, how can I fix this?

<img width="551" alt="screen shot 2017-08-05 at 07 28 13" src="https://user-images.githubusercontent.com/4089219/28994878-9c766cd2-79af-11e7-9656-7173f576fa0f.png">

**Comment by vadviktor** [comment]
@so77id I'd suggest thoroughly reading the README:

>  BULLETTRAIN_PROMPT_SEPARATE_LINE | true | Make the prompt span across two lines

:) hope this helps you understand how it works and how versatile it is to customise behaviour.

**Comment by so77id** [comment]
don't works for me.  :'(

**Comment by vadviktor** [comment]
Can you show me the section in your `.zshrc` file where you configure the theme, please?

**Comment by egilbert** [comment]
Actually, if you look closely, *all* separators are shifted down. My guess is look at your font?

**Comment by vadviktor** [comment]
OH! I misunderstood the "separator" for the prompt line separator. Now I see whate @so77id was referring to. So yes, on Linux I usually experience such anomalies but that is due to the used font's and the terminal software's nature. We can't help that but can offer better combinations.

**Comment by so77id** [comment]
The truth is I'm on mac with OS x, when using iterm2 this problem is solved, but I prefer the native mac terminal, so I decided to remove the "separator" and everything works ok

**Comment by Ruberto** [comment]
@so77id How did you remove the "separator"?

**Comment by vadviktor** [comment]
Just marking this issue closed as per @so77id 's comment. Please continue discussing as needed.
