### ISSUE TITLE
Feature request: rust segment

### ISSUE THREAD

**Issue by dbkaplun** [caiogondim/bullet-train.zsh#258]
Would be great if there was a Rust segment! Thanks for considering!

**Comment by caiogondim** [comment]
Hi Dan,

How do you see it working?

**Comment by dbkaplun** [comment]
Hi! I am thinking that we can detect a `Cargo.toml` file in a parent directory, and if so, show the rust version as a segment:
```sh
$  rustc -V
rustc 1.25.0-nightly (3d292b793 2018-02-03)
```
It might look like `🦀 1.25.0-nightly`. 😄
