### ISSUE TITLE
Shows my laptop's name instead of `~` for home.

### ISSUE THREAD

**Issue by m-sameer** [caiogondim/bullet-train.zsh#260]
![screenshot from 2018-02-01 23-42-35](https://user-images.githubusercontent.com/28915865/35695213-e0b4670e-07a9-11e8-8164-6a08592b81e7.png)

I would like to change the text in black to `~` and make the black to white.

**Comment by runofthemill** [comment]
just remove the `context` prompt part in `BULLETTRAIN_PROMPT_ORDER=()`

**Comment by m-sameer** [comment]
Okay. Thank you so much. It worked.
