### ISSUE TITLE
Themes not working on Mac

### ISSUE THREAD

**Issue by ElegantLin** [caiogondim/bullet-train.zsh#272]
The theme is not working on Mac 10.13.3.
The version of oh-my-zsh is 5.3 version.
I modified the .zshrc file and I got a terminal like this,
![screen shot 2018-04-01 at 12 37 57 am](https://user-images.githubusercontent.com/16239478/38165384-fba39b70-3544-11e8-89fa-31eb0a74f642.png)

**Comment by caiogondim** [comment]
You need a patched font as described in the Requirements sections of README
![image](https://user-images.githubusercontent.com/33044/38201940-0691934c-3668-11e8-8d3f-3dbf6fa77a9b.png)

**Comment by VixsTy** [comment]
It's working like a charm on mac. You just need to install and use a patched font like asked in requirements.

You can close this ticket.
