### ISSUE TITLE
Disable time prompt

### ISSUE THREAD

**Issue by marcosps** [caiogondim/bullet-train.zsh#281]
Hi, is there a way to disable the time segment? As I currently use tmux, it would be a duplicated information in my screen.

**Comment by caiogondim** [comment]
Hi @marcosps 
You can omit the segments you don't want https://github.com/caiogondim/bullet-train.zsh#order

**Comment by marcosps** [comment]
@caiogondim that right, I should had read the README before asking, thanks for the help!
