### ISSUE TITLE
Doesn't display conda virtual env name

### ISSUE THREAD

**Issue by MagicalBomb** [caiogondim/bullet-train.zsh#306]
there was no snake and conda virtual environment name in my zsh prompt when I activated a python virtual environment, I don't know why.
may I make some mistakes or just a bug ?

<img width="787" alt="image" src="https://user-images.githubusercontent.com/10193482/52402057-4178b400-2afe-11e9-9271-c60ade0ce559.png">
<img width="379" alt="image" src="https://user-images.githubusercontent.com/10193482/52402071-48072b80-2afe-11e9-9ca4-942f57129148.png">

**Comment by Angryrou** [comment]
They have not provided conda env, you can add this feature by mimicing how `virtualenv` works. 
E.g., I did like [this](https://github.com/caiogondim/bullet-train.zsh/issues/282#issuecomment-516266791). 

Also make sure you add `conda config --set changeps1 False` in your `.bashrc` or `.zshrc` file

**Comment by xwzp** [comment]
> They have not provided conda env, you can add this feature by mimicing how `virtualenv` works.
> E.g., I did like [this](https://github.com/caiogondim/bullet-train.zsh/issues/282#issuecomment-516266791).
> 
> Also make sure you add `conda config --set changeps1 False` in your `.bashrc` or `.zshrc` file

Sorry to reply now, I'm so grateful
